alias ll='ls -l'
alias lt='ls -lt'
alias ll='ls -lF'
alias la='ls -A'
alias l='ls -CF'
alias promptmach='export PS1="\h> "'
alias promptpath='export PS1="\w> "'
alias promptuser='export PS1="\u> "'
alias promptnum='export PS1="\#> "'
alias promptfull='export PS1="\h \#> "'
